name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Test install locally
        run: |
          chmod +x install.sh
          ./install.sh --local
          command -v blindsort
      - name: Test --help and -h
        run: |
          blindsort --help
          blindsort -h
      - name: Test --version and -v
        run: |
          blindsort --version
          blindsort -v
      - name: Test uninstall
        run: |
          chmod +x uninstall.sh
          ./uninstall.sh --local
          test ! -f $HOME/.local/bin/blindsort
